spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

agrocenter.security.jwt.issuer-uri=${COGNITO_ISSUER_URI}
agrocenter.security.jwt.jwk-set-uri=${COGNITO_JWK_SET_URI}
agrocenter.security.jwt.audience=${COGNITO_AUDIENCE}
agrocenter.inventory.base-url=${INVENTORY_SERVICE_URL:${MS_INVENTARIO_URL:http://ms-inventario-svc:8081}}
