spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

agrocenter.security.jwt.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DBCBjL67J}
agrocenter.security.jwt.jwk-set-uri=${COGNITO_JWK_SET_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DBCBjL67J/.well-known/jwks.json}
agrocenter.security.jwt.audience=${COGNITO_AUDIENCE:agrocenter-api}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DBCBjL67J}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${COGNITO_JWK_SET_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_DBCBjL67J/.well-known/jwks.json}
agrocenter.inventory.base-url=${INVENTORY_SERVICE_URL:${MS_INVENTARIO_URL:http://internal-agrocenter-bff-alb:8080}}
agrocenter.inventory.connect-timeout=${INVENTORY_CONNECT_TIMEOUT:5s}
agrocenter.inventory.read-timeout=${INVENTORY_READ_TIMEOUT:10s}
