spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

agrocenter.security.dev.jwt-secret=${DEV_JWT_SECRET}
agrocenter.security.dev.issuer=${DEV_JWT_ISSUER:http://localhost:8081/dev-issuer}
agrocenter.security.dev.audience=${COGNITO_AUDIENCE:agrocenter-api}
